const scenarios = [
    {
        id: 1,
        gameVariant: "No-Limit Hold'em",
        title: "Pre-flop: Obrona Blinda",
        description: "Jesteś na Big Blindzie. Gracz na pozycji Cutoff (agresywny) otwiera za 2.5BB. Wszyscy do Ciebie pasują. Masz 100BB stacka.",
        potSize: "3.5 BB",
        heroHand: "A♦️ 9♣️",
        board: "Brak",
        actionHistory: "Cutoff podbija do 2.5 BB. Button pasuje. Small Blind pasuje.",
        options: ["Spasuj", "Sprawdź", "3-bet do 9 BB"],
        correctAnswer: "3-bet do 9 BB",
        explanation: "Poprawna odpowiedź to 3-bet. A9s jest zbyt silne na sam call z tej pozycji przeciwko agresywnemu graczowi z Cutoff. 3-bet pozwala przejąć inicjatywę i często wygrać pulę od razu."
    },
    {
        id: 2,
        gameVariant: "No-Limit Hold'em",
        title: "Turn: Scare card",
        description: "Gra cashowa, stacki po 100BB. Podbiłeś pre-flop z UTG, jeden gracz sprawdził na Buttonie.",
        potSize: "17.5 BB",
        heroHand: "K♠️ K♦️",
        board: "J♠️ 8♣️ 3❤️ A♠️",
        actionHistory: "Na flopie (J-8-3) zabetowałeś, a przeciwnik sprawdził. Na turnie spada As.",
        options: ["Check", "Bet 1/3 puli", "Bet 2/3 puli"],
        correctAnswer: "Check",
        explanation: "Poprawna odpowiedź to check. As jest 'straszną kartą' (scare card), która trafia w dużą część zakresu przeciwnika, który sprawdzał na flopie. Dalsze betowanie byłoby ryzykowne. Check pozwala na kontrolę puli i ewentualne złapanie blefu."
    },
    {
        id: 3,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Third Street: Startowa ręka",
        description: "Otrzymujesz pierwsze trzy karty. Jesteś na środkowej pozycji.",
        potSize: "Zmienna (zależna od ante)",
        heroHand: "(A♠️ 2♠️) 3♠️",
        board: "Twoja odkryta karta to 3♠️. U przeciwników widzisz: K♦️, 7♣️, Q❤️.",
        actionHistory: "Gracz z najniższą kartą (bring-in) wpłacił obowiązkowy zakład. Akcja dochodzi do Ciebie.",
        options: ["Spasuj", "Uzupełnij (Complete)", "Sprawdź (jeśli można)"],
        correctAnswer: "Uzupełnij (Complete)",
        explanation: "Poprawna odpowiedź to uzupełnienie (podbicie). Masz trzy karty do koloru, strita i najlepszego możliwego układu low (A-2-3). To jest premium ręka startowa w Stud8, którą należy rozgrywać agresywnie."
    },
    {
        id: 4,
        gameVariant: "Pot-Limit Omaha",
        title: "Flop: Silny draw",
        description: "Gra cashowa PLO100, stacki po 100BB. Jesteś na Buttonie.",
        potSize: "13.5 BB",
        heroHand: "A♠️ K♠️ T♦️ 9♦️",
        board: "Q♠️ J♠️ 5♦️",
        actionHistory: "Gracz z pozycji UTG zagrał check. Gracz z MP również czeka.",
        options: ["Check", "Bet 1/2 puli", "Bet całą pulę"],
        correctAnswer: "Bet całą pulę",
        explanation: "Poprawna odpowiedź to bet za pulę. Masz potężne combo draw: nut flush draw i gutshot do nut straight (potrzebujesz króla). W PLO takie ręce rozgrywa się bardzo agresywnie, aby budować pulę i maksymalizować equity. Check jest zbyt pasywny."
    },
    {
        id: 5,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Third Street: Dwie wysokie karty i niska",
        description: "Gra cashowa z limitem. Jesteś na późnej pozycji.",
        potSize: "2.5 małej stawki",
        heroHand: "(A♠️ K♠️) 2♠️",
        board: "Twoja odkryta karta to 2♠️. Przed Tobą gracz z 7❤️ podbił.",
        actionHistory: "Dwóch graczy weszło za limpa, gracz z 7❤️ podbił (complete). Akcja do Ciebie.",
        options: ["Spasuj", "Sprawdź", "Przebij (3-bet)"],
        correctAnswer: "Przebij (3-bet)",
        explanation: "To jest bardzo silna ręka startowa. Masz potencjał na kolor nuts (Hi), strita nuts (Hi) oraz niski układ (Lo) z A-2. Przebicie jest najlepszym zagraniem, aby budować pulę i wyrzucić graczy ze słabszymi rękami."
    },
    {
        id: 6,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Third Street: Niska para w dziurze",
        description: "Jesteś na środkowej pozycji. Nikt jeszcze nie wszedł do gry.",
        potSize: "Ante",
        heroHand: "(3♦️ 3♣️) 8♠️",
        board: "Twoja odkryta karta to 8♠️. Karta bring-in to 2♣️.",
        actionHistory: "Gracz z 2♣️ wpłacił bring-in. Wszyscy przed Tobą spasowali.",
        options: ["Spasuj", "Uzupełnij (Complete)", "Sprawdź"],
        correctAnswer: "Uzupełnij (Complete)",
        explanation: "Ukryta niska para z kartą do Lo to silna ręka. Możesz złapać trójkę, która będzie dobrze zamaskowana, a jednocześnie masz draw do niskiego układu. Uzupełnienie zakładu (podbicie) jest standardowym zagraniem, aby przejąć inicjatywę."
    },
    {
        id: 7,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Fourth Street: Złapanie idealnej karty Lo",
        description: "Zacząłeś z (A♣️ 2♦️) 6♣️. Przeciwnik podbił na trzeciej ulicy z K❤️.",
        potSize: "5 małych stawek",
        heroHand: "(A♣️ 2♦️) 6♣️ 3♦️",
        board: "Twoje karty odkryte: 6♣️ 3♦️. Przeciwnik: K❤️ J♣️.",
        actionHistory: "Na trzeciej ulicy sprawdziłeś podbicie przeciwnika. Teraz on zagrywa bet.",
        options: ["Spasuj", "Sprawdź", "Podbij"],
        correctAnswer: "Podbij",
        explanation: "Złapałeś idealną kartę (trójkę), która daje Ci cztery karty do najlepszego układu niskiego (A-2-3-6). Twoja ręka jest teraz bardzo silna i powinieneś grać ją agresywnie, aby budować pulę i wywierać presję na przeciwniku, który prawdopodobnie ma tylko układ Hi."
    },
    {
        id: 8,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Fourth Street: Para asów kontra niski draw",
        description: "Zacząłeś z (A♠️ 6♦️) A♣️. Podbiłeś, sprawdził Cię gracz z 4♠️.",
        potSize: "5 małych stawek",
        heroHand: "(A♠️ 6♦️) A♣️ T♠️",
        board: "Twoje karty odkryte: A♣️ T♠️. Przeciwnik: 4♠️ 8♠️.",
        actionHistory: "Przeciwnik zagrał check.",
        options: ["Check", "Bet"],
        correctAnswer: "Bet",
        explanation: "Masz parę asów, co jest silnym układem wysokim. Przeciwnik pokazuje dwie niskie karty w kolorze, co daje mu silny draw do Lo i koloru. Musisz betować dla wartości i aby 'kazać mu płacić' za dobieranie. Check dałby mu darmową kartę."
    },
    {
        id: 9,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Fifth Street: Podwójne wysokie stawki",
        description: "Masz A-2-3-7-8, czyli gotowy układ Lo. Przeciwnik ma parę króli (K-K-5).",
        potSize: "12 małych stawek",
        heroHand: "(A♣️ 2♦️) 3♣️ 7♦️ 8♠️",
        board: "Twoje: 3♣️ 7♦️ 8♠️. Przeciwnik: (X X) K♦️ K♣️ 5♠️.",
        actionHistory: "Przeciwnik zagrywa bet. Od tej ulicy stawki są podwójne.",
        options: ["Spasuj", "Sprawdź", "Podbij"],
        correctAnswer: "Podbij",
        explanation: "Masz już gotowy, bardzo silny układ Lo i jesteś faworytem do wygrania połowy puli. Przeciwnik ma tylko parę króli. Podbicie jest konieczne, aby budować pulę i maksymalizować zysk z układu Lo. Sprawdzenie byłoby zbyt pasywne."
    },
    {
        id: 10,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Fifth Street: Czy blefować?",
        description: "Zaczynałeś z drawem do Lo, ale złapałeś parę. Przeciwnik również dobierał do Lo.",
        potSize: "10 małych stawek",
        heroHand: "(A♣️ 4♦️) 5♣️ 8♦️ 8♠️",
        board: "Twoje: 5♣️ 8♦️ 8♠️. Przeciwnik: (X X) 2♠️ 6♣️ 7♦️.",
        actionHistory: "Przeciwnik, który pierwszy pokazał niskie karty, gra check.",
        options: ["Check", "Bet"],
        correctAnswer: "Bet",
        explanation: "Twój draw do Lo jest martwy z powodu pary ósemek. Jednak przeciwnik, który ma bardzo wyraźny draw do Lo (2-6-7), zagrał check. To oznaka słabości. Twój bet może reprezentować siłę (np. trójkę) i zmusić go do spasowania lepszego drawu. To dobry moment na semi-blef."
    },
    {
        id: 11,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Sixth Street: Straszna karta dla przeciwnika",
        description: "Masz trójkę. Przeciwnik dobierał do koloru.",
        potSize: "10 dużych stawek",
        heroHand: "(7♠️ 7♦️) A♣️ K♦️ Q♦️ 7♣️",
        board: "Twoje: A♣️ K♦️ Q♦️ 7♣️. Przeciwnik: (X X) 4♦️ 9♦️ J♦️ 2♠️.",
        actionHistory: "Przeciwnik, mający cztery karty do koloru, gra check.",
        options: ["Check", "Bet"],
        correctAnswer: "Bet",
        explanation: "Złapałeś trójkę siódemek. Twoje odkryte karty (K-Q w kolorze) mogły wcześniej odstraszać. Kiedy przeciwnik nie skompletował koloru na szóstej ulicy i zagrał check, musisz betować dla wartości. Twoja trójka jest prawie na pewno najlepszym układem Hi."
    },
    {
        id: 12,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Sixth Street: Być 'quartered'?",
        description: "Ty i Twój przeciwnik macie oczywiste układy Lo. Oboje macie A-2-3-X-X.",
        potSize: "12 dużych stawek",
        heroHand: "(A♣️ 2♦️) 3♣️ 7♦️ 8♠️ 4♥",
        board: "Twoje: 3♣️ 7♦️ 8♠️ 4♥. Przeciwnik: (X X) A♦️ 2♠️ 5♠️ 6♥.",
        actionHistory: "Przeciwnik zagrywa bet.",
        options: ["Spasuj", "Sprawdź", "Podbij"],
        correctAnswer: "Sprawdź",
        explanation: "Oboje macie świetne układy Lo. Ty masz 8-7-4-3-2-A, a on 6-5-2-A. On ma lepszy układ Lo (6-low vs 8-low). Nie masz szans na Hi. Jeśli sprawdzisz, przegrasz Lo, ale nie ma puli Hi do wygrania. Spasowanie jest jednak zbyt słabe, bo pula jest duża. Jeśli na river spadnie niska karta, możecie mieć taki sam układ Lo (np. oboje A-2-3-4-5) i podzielicie się połową puli (dostaniesz 1/4, czyli 'quartered'). Sprawdzenie to najlepsza opcja."
    },
    {
        id: 13,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Seventh Street: Sprawdzić z dwiema parami?",
        description: "Ostatnia karta jest zakryta. Dobrałeś do dwóch par.",
        potSize: "15 dużych stawek",
        heroHand: "(A♣️ K♦️) A♦️ 5♣️ T♣️ 8♠️ (K♠️)",
        board: "Twoje widoczne: A♦️ 5♣️ T♣️ 8♠️. Przeciwnik: (X X) Q♠️ Q♣️ 4♠️ 7♦️ (X).",
        actionHistory: "Przeciwnik, który od początku pokazywał parę dam, zagrał bet.",
        options: ["Spasuj", "Sprawdź"],
        correctAnswer: "Sprawdź",
        explanation: "Masz dwie pary, asy i króle, co jest silnym układem Hi. Przeciwnik betuje, reprezentując trójkę dam lub lepszy układ. Jednak pula jest już bardzo duża, a on mógł nie poprawić swojej pary. Sprawdzenie (call) jest poprawne, ponieważ Twoja ręka jest zbyt silna, by ją spasować (łapiesz blefy), ale prawdopodobnie niewystarczająco silna, by podbijać dla wartości."
    },
    {
        id: 14,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Seventh Street: Blef catch z asem high",
        description: "Dobierałeś do Lo i koloru, ale nic nie trafiłeś. Przeciwnik też nic nie pokazał.",
        potSize: "10 dużych stawek",
        heroHand: "(A♠️ 2♠️) 6♠️ 8♦️ Q♣️ K♥ (4♦️)",
        board: "Twoje widoczne: 6♠️ 8♦️ Q♣️ K♥. Przeciwnik: (X X) 3♣️ 5♦️ T♦️ J♣️ (X).",
        actionHistory: "Przeciwnik, który nie pokazał ani pary, ani drawu do Lo, zagrywa bet.",
        options: ["Spasuj", "Sprawdź"],
        correctAnswer: "Sprawdź",
        explanation: "To klasyczny 'bluff catch'. Żaden z was nie pokazuje siły. Twój układ Hi to tylko As-high. Jednak board przeciwnika jest równie słaby. Jego bet na river w tak dużą pulę, bez reprezentowania czegokolwiek, wygląda na czysty blef. Sprawdzenie z Asem-high jest tutaj często opłacalne."
    },
    {
        id: 15,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Third Street: Trzy karty do niskiego strita w kolorze",
        description: "Gra wieloosobowa, jesteś na wczesnej pozycji.",
        potSize: "Ante",
        heroHand: "(4♠️ 5♠️) 6♠️",
        board: "Twoja odkryta karta to 6♠️. Bring-in to 2♣️.",
        actionHistory: "Bring-in zapłacony. Akcja do Ciebie.",
        options: ["Spasuj", "Uzupełnij (Complete)", "Sprawdź"],
        correctAnswer: "Uzupełnij (Complete)",
        explanation: "Trzy kolejne karty w kolorze, nawet jeśli są średnie, mają ogromny potencjał. Możesz skompletować strita, kolor, a nawet pokera. Masz również draw do Lo. To ręka, którą chcesz rozgrywać agresywnie od początku, aby budować pulę."
    },
    {
        id: 16,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Fourth Street: 'Scare card' dla Ciebie",
        description: "Zaczynałeś z A-2-3. Przeciwnik miał króla. Teraz złapałeś parę.",
        potSize: "6 małych stawek",
        heroHand: "(A♣️ 2♦️) 3♣️ A♠️",
        board: "Twoje: 3♣️ A♠️. Przeciwnik: K♥ 7♦️.",
        actionHistory: "Przeciwnik zagrał bet.",
        options: ["Spasuj", "Sprawdź", "Podbij"],
        correctAnswer: "Podbij",
        explanation: "Złapanie asa jest tutaj fantastyczną kartą. 'Psuje' Ci draw do Lo, ale daje parę asów, najlepszy układ Hi. Twój as jest też 'straszną kartą' dla przeciwnika z królem. Powinieneś podbić, aby natychmiast przejąć kontrolę nad rozdaniem i grać o pulę Hi."
    },
    {
        id: 17,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Fifth Street: Fold z gotowym Lo?",
        description: "Masz gotowy, ale słaby układ Lo (8-low). Przeciwnik pokazuje trójkę.",
        potSize: "11 dużych stawek",
        heroHand: "(2♣️ 4♦️) 5♣️ 7♦️ 8♠️",
        board: "Twoje: 5♣️ 7♦️ 8♠️. Przeciwnik: (X X) K♦️ K♣️ K♠️.",
        actionHistory: "Przeciwnik z trójką króli zagrywa bet. Dwóch innych graczy już spasowało.",
        options: ["Spasuj", "Sprawdź"],
        correctAnswer: "Spasuj",
        explanation: "Twój układ Lo jest bezwartościowy, ponieważ przeciwnik ma trójkę króli, co jest potężnym układem Hi i nie ma szans na podział puli. Nie masz redrawu do Hi. Musisz spasować, mimo że masz gotowy układ Lo. Dalsze inwestowanie pieniędzy to błąd."
    },
    {
        id: 18,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Sixth Street: Value bet z kolorem",
        description: "Skompletowałeś kolor. Przeciwnik ma cztery niskie karty.",
        potSize: "14 dużych stawek",
        heroHand: "(A♦️ K♦️) 5♦️ 8♣️ T♦️ 2♦️",
        board: "Twoje: 5♦️ 8♣️ T♦️ 2♦️. Przeciwnik: (X X) A♠️ 3♠️ 6♣️ 7♥.",
        actionHistory: "Przeciwnik zagrał check.",
        options: ["Check", "Bet"],
        correctAnswer: "Bet",
        explanation: "Masz kolor nuts (Hi). Przeciwnik ma bardzo prawdopodobny układ Lo. Musisz betować dla wartości. On prawie na pewno sprawdzi, licząc na wygranie połowy puli ze swoim Lo. Check byłby stratą wartości."
    },
    {
        id: 19,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Seventh Street: Cienki value bet ze stritem",
        description: "Skompletowałeś strita A-5. Na stole leży możliwy kolor i lepszy strit.",
        potSize: "18 dużych stawek",
        heroHand: "(A♣️ 2♦️) 3♣️ 4♦️ K♠️ Q♠️ (5♠️)",
        board: "Twoje widoczne: 3♣️ 4♦️ K♠️ Q♠️. Przeciwnik: (X X) J♠️ T♠️ 6♣️ 7♦️ (X).",
        actionHistory: "Przeciwnik zagrał check.",
        options: ["Check", "Bet"],
        correctAnswer: "Bet",
        explanation: "Masz strita, ale są możliwe lepsze układy (kolor, wyższy strit). Jednak przeciwnik, który pokazywał draw do strita i koloru, zagrał check. To sugeruje, że nie skompletował swojego układu. Powinieneś zagrać mały bet dla wartości (thin value bet). Często sprawdzi Cię z dwiema parami lub niższą ręką."
    },
    {
        id: 20,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Third Street: Para króli, ale zła karta towarzysząca",
        description: "Rozdanie heads-up.",
        potSize: "Ante",
        heroHand: "(K♦️ K♣️) Q♠️",
        board: "Twoja odkryta karta to Q♠️. Przeciwnik pokazuje 5♣️.",
        actionHistory: "Przeciwnik (z niższą kartą) wpłacił bring-in. Akcja do Ciebie.",
        options: ["Spasuj", "Uzupełnij (Complete)"],
        correctAnswer: "Uzupełnij (Complete)",
        explanation: "Ukryta para króli to bardzo silna ręka startowa, mimo że Dama jako karta odkryta nie pomaga. Przeciwko jednej niskiej karcie jesteś ogromnym faworytem. Musisz podbić, aby od razu budować pulę."
    },
    {
        id: 21,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Fourth Street: Otwarty strit draw vs para",
        description: "Zaczynałeś z 5-6-7. Przeciwnik miał parę ósemek.",
        potSize: "5 małych stawek",
        heroHand: "(5♣️ 6♦️) 7♣️ 8♠️",
        board: "Twoje: 7♣️ 8♠️. Przeciwnik: 8♦️ 8♥.",
        actionHistory: "Przeciwnik zagrał bet.",
        options: ["Spasuj", "Sprawdź", "Podbij"],
        correctAnswer: "Podbij",
        explanation: "Trafienie ósemki dało Ci otwarty strit draw (OESD) i parę. Masz też draw do Lo. Twoja ręka ma teraz ogromne equity przeciwko parze ósemek przeciwnika. Podbicie (semi-blef) jest najlepszym zagraniem, aby wywrzeć presję i zmaksymalizować potencjalny zysk."
    },
    {
        id: 22,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Fifth Street: Fold z dwiema parami?",
        description: "Masz dwie pary, ale przeciwnik pokazuje otwarty strit i flush draw.",
        potSize: "12 dużych stawek",
        heroHand: "(T♣️ T♦️) 7♣️ 7♠️ K♥",
        board: "Twoje: 7♣️ 7♠️ K♥. Przeciwnik: (X X) 8♠️ 9♠️ T♠️.",
        actionHistory: "Przeciwnik zagrał bet.",
        options: ["Spasuj", "Sprawdź", "Podbij"],
        correctAnswer: "Spasuj",
        explanation: "Mimo że masz dwie pary, Twoja sytuacja jest bardzo zła. Przeciwnik ma potężny draw (strit, kolor, strit w kolorze) i jeśli trafi, prawie na pewno przegrasz. Ponieważ on betuje, a stawki są już wysokie, dalsze inwestowanie w pulę jest zbyt ryzykowne. To jest trudny, ale poprawny fold."
    },
    {
        id: 23,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Sixth Street: Czy mój strit jest dobry?",
        description: "Masz strita do ósemki. Przeciwnik pokazuje cztery karty do koloru.",
        potSize: "13 dużych stawek",
        heroHand: "(4♣️ 5♦️) 6♣️ 7♠️ 8♥ 2♦️",
        board: "Twoje: 6♣️ 7♠️ 8♥ 2♦️. Przeciwnik: (X X) A♠️ K♠️ Q♠️ 3♠️.",
        actionHistory: "Przeciwnik z czterema pikami zagrywa bet.",
        options: ["Spasuj", "Sprawdź"],
        correctAnswer: "Sprawdź",
        explanation: "Masz strita (Hi) i gotowy układ 8-low (Lo). Przeciwnik betuje, reprezentując skompletowany kolor. Nie możesz podbijać, bo prawdopodobnie przegrywasz pulę Hi. Nie możesz też spasować, bo masz pewną połowę puli ze swoim Lo. Sprawdzenie jest jedynym logicznym zagraniem."
    },
    {
        id: 24,
        gameVariant: "Stud8 (Hi-Lo)",
        title: "Seventh Street: Value bet czy check-raise?",
        description: "Trafiłeś fulla na river. Przeciwnik prawdopodobnie ma strita lub kolor.",
        potSize: "20 dużych stawek",
        heroHand: "(A♣️ A♦️) 5♣️ K♠️ T♠️ J♠️ (A♠️)",
        board: "Twoje widoczne: 5♣️ K♠️ T♠️ J♠️. Przeciwnik: (X X) 6♠️ 7♠️ 8♠️ 9♠️ (X).",
        actionHistory: "Akcja dochodzi do Ciebie jako pierwszego.",
        options: ["Check", "Bet"],
        correctAnswer: "Check",
        explanation: "Masz potężnego fulla (asy na króle), ale Twój board jest bardzo 'mokry'. Przeciwnik, widząc cztery piki, może mieć kolor. Jeśli zagrasz bet, może spasować słabsze układy. Lepszym zagraniem jest check, który indukuje blef lub value bet od przeciwnika ze stritem lub kolorem. Wtedy możesz zagrać check-raise i zgarnąć maksymalną wartość."
    }
];
